import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from '../componenets/Navbar';
import Footer from "@/componenets/Footer";
import { CartProvider } from "@/context/CartContext";
import { RatingsProvider } from "@/context/RatingsContext";
import { Toaster } from 'react-hot-toast';
import { WishlistProvider } from "@/context/WishlistContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       <CartProvider>
        <WishlistProvider>
          <RatingsProvider>
            <Navbar/>
            <main className="max-w-7xl mx-auto px-4 py-6" >
              {children}
            </main>
            <Footer/>
            <Toaster position="top-right" />
          </RatingsProvider>
        </WishlistProvider>
        </CartProvider>
    
      </body>
    </html>
  );
}


